name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build and deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a photo-filter-mini
          heroku container:release web -a photo-filter-mini
